# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FORM.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from abc import abstractmethod
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QMessageBox
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import pyqtSlot
from PyQt5.QtCore import pyqtSignal, QUrl, QUrlQuery
from PyQt5.QtNetwork import QNetworkAccessManager, QNetworkReply, QNetworkRequest,QNetworkCookieJar
from PyQt5 import QtNetwork
from datetime import datetime
import urllib.parse
import urllib.request 


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 231, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 71, 21))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(150, 70, 341, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 101, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 308, 101, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 348, 101, 16))
        self.label_5.setObjectName("label_5")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(150, 348, 70, 17))
        self.checkBox.setObjectName("checkBox")
        self.checkBox.setChecked(True)
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(220, 348, 91, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 378, 101, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 378, 341, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 448, 101, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(600, 300, 101, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 420, 101, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(500, 70, 71, 21))
        self.label_10.setObjectName("label_10")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(520, 70, 341, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(150, 308, 341, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(150, 448, 341, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(150, 420, 341, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(150, 110, 341, 191))
        self.calendarWidget.setObjectName("calendarWidget")
        #self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        #self.pushButton.setGeometry(QtCore.QRect(150, 490, 131, 51))
        #self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 490, 131, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton_2.clicked.connect(self.clicked_btn)
        self.checkBox.toggled.connect(self.checkbox_btn)
        self.checkBox_2.toggled.connect(self.checkbox2_btn)
    
    def checkbox_btn(self, state):
        if self.checkBox.isChecked() == True:
            self.checkBox_2.setChecked(False)
            
            
            #self.label_8.setStyleSheet("color:green")
        else:
            self.checkBox.setChecked(False)
            
            #self.label_8.setStyleSheet("color:red")
    
    def checkbox2_btn(self, state):
        if self.checkBox_2.isChecked() == True:
            self.checkBox.setChecked(False)
            
            #self.label_8.setStyleSheet("color:green")
        else:
            self.checkBox_2.setChecked(False)
            
            #self.label_8.setStyleSheet("color:red")

    
    def clicked_btn(self):
        now = datetime.now()
        waktu = now.strftime("%d/%m/%Y %H:%M:%S")

        jeniskelamin = str(self.comboBox.currentText())
        pekerjaanpasien = str(self.comboBox_2.currentText())
        if self.checkBox.isChecked() == True:
            statusnikah = 'Kawin'
        elif self.checkBox_2.isChecked() == True:
            statusnikah = 'Belum Kawin'
        else:
            statusnikah = 'Kosong'
        
        
        namapasien = self.lineEdit.text()
        kotapasien = self.lineEdit_2.text()
        lahirpasien = self.calendarWidget.selectedDate().toString()


        if self.comboBox_3.currentIndex() == 0:
            pilihandokter = "5053782348:AAFv4Dn-DwiW2kv8gEHcplmv_NWpJeC8Gdk" #dokter umum
            #chatid = "1398822979" #chat id rita
        elif self.comboBox_3.currentIndex() == 1:
            pilihandokter = "5055872361:AAF7SvlXPItk5S3cS1oYmpFW-zG1xrctS5Q" #spesialis kandungan
            #chatid = "1398822979" 
        elif self.comboBox_3.currentIndex() == 2:
            pilihandokter = "5012230148:AAFmIRXr2_04IiqUANCkLeduYPsJP_IKqqg" #spesialis anak

        elif self.comboBox_3.currentIndex() == 3:
            pilihandokter = "5049996996:AAGfd5cGbqjgUvt_jMWrkBldTqIbWAKPkoE" # spesialis penyakit dalam
        elif self.comboBox_3.currentIndex() == 4:
            pilihandokter = "5033401776:AAG0M26Bwk-XdukgLwP-kCuEx-UtW4Hzs0A" #spesialis bedah
        else:
            pilihandokter = "2070076356:AAHjDS_mB9IE-1sBwoxTDzA8y05TMb3XIi8" #form RS bot

        urlawal = 'https://api.telegram.org/bot' +pilihandokter+ '/sendMessage?chat_id=1398822979&parse_mode=html&text='
        pesan1 = '<b>PASIEN BARU</b>%0AWaktu Submit : '+waktu+'%0A%0ANama Pasien : '+namapasien+'%0AKota : '+kotapasien+'%0ATanggal Lahir : '+lahirpasien+''
        pesan2 = '%0AJenis Kelamin : '+jeniskelamin+'%0APekerjaan : '+pekerjaanpasien+'%0AStatus Nikah : '+statusnikah+'%0ASpesialis yang dipilih : '+self.comboBox_3.currentText()
        url = urlawal+pesan1+pesan2
        req = QtNetwork.QNetworkRequest(QUrl(url))

        self.nam = QtNetwork.QNetworkAccessManager()
        self.nam.finished.connect(self.handleResponse)
        self.nam.get(req)

        #ngetest smsnya jangan banyak banyak ya bang, terbatas kuota API nya
        isisms = 'Pasien Yth, anda terdaftar di RS SAN JOSE, Sp. '+self.comboBox_3.currentText()+', Tgl 15/02/2022 jam 08.00. Mohon datang 1 jam sebelum jadwal. Terima kasih.'
        apisms = urllib.request.urlopen('https://websms.co.id/api/smsgateway?token=93916b1da58f544ddf99a2d3511117d3&to='+self.lineEdit_3.text()+'&msg=' +urllib.parse.quote_plus(isisms))
        apisms_response = apisms.read()

        print(apisms)


    def handleResponse(self, reply):

        er = reply.error()

        if er == QtNetwork.QNetworkReply.NoError:

            bytes_string = reply.readAll()
            print(str(bytes_string, 'utf-8'))
            self.label_8.setStyleSheet("color:green")
            self.label_8.setText("TERKIRIM")

        else:
            print("Error occured: ", er)
            print(reply.errorString())
            self.label_8.setStyleSheet("color:red")
            self.label_8.setText('GAGAL')

 




    
  
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "FORM PENDAFTARAN RUMAH SAKIT"))
        self.label_2.setText(_translate("MainWindow", "Nama"))
        self.label_3.setText(_translate("MainWindow", "Tanggal Lahir"))
        self.label_4.setText(_translate("MainWindow", "Jenis Kelamin"))
        self.label_5.setText(_translate("MainWindow", "Status"))
        self.checkBox.setText(_translate("MainWindow", "Kawin"))
        self.checkBox_2.setText(_translate("MainWindow", "Belum Kawin"))
        self.label_6.setText(_translate("MainWindow", "Kota"))
        self.label_7.setText(_translate("MainWindow", "Pekerjaan"))
        self.label_9.setText(_translate("MainWindow", "Pilihan Dokter"))
        self.label_10.setText(_translate("MainWindow", "HP"))
        self.comboBox.setItemText(0, _translate("MainWindow", " "))
        self.comboBox.setItemText(1, _translate("MainWindow", "Laki-Laki"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Perempuan"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", " "))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Wiraswasta"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Pelajar"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Karyawan"))

        self.comboBox_3.setItemText(0, _translate("MainWindow", "Dokter Umum"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Kandungan"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Anak"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Penyakit Dalam"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "Bedah"))
        #self.pushButton.setText(_translate("MainWindow", "Cancel"))
        self.pushButton_2.setText(_translate("MainWindow", "Submit"))
        self.label_8.setText(_translate("MainWindow", "STATUS"))
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
